language: php

php:
  - 5.6
  #- 7.0
  #- nightly
  #- hhvm

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

scripts: phpunit ./tests